language: C
dist: trusty
sudo: true

before_install:
- sudo apt-get update -qq
- sudo apt-get install --assume-yes asciidoc valgrind

script:
- ./autogen.sh
- ./configure
- make
- make test
- ./configure --enable-debug --enable-transparent --enable-reverse
- make
- make test
- make valgrind-test
- make distcheck
